substitutions:
  _SERVICE: "cloud-run-ktor-hello"
  _REGION: "europe-west1"
  _REPO: "cloud-run-ktor-hello-repo"
steps:
  - name: 'gradle:9.0.0-jdk21'
    id: 'build-image'
    dir: '.'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    entrypoint: bash
    args:
      - -c
      - |
        ./gradlew jib --no-daemon -Djib.container.environment=PROJECT_ID=$PROJECT_ID -Djib.to.image="europe-west1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/cloud-run-ktor-hello" -Djib.to.tags="latest,${COMMIT_SHA}"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=europe-west1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/cloud-run-ktor-hello:${COMMIT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --execution-environment=gen2
