substitutions:
  _SERVICE: "cloud-run-ktor-hello"
  _REGION: "europe-west1"
  _REPO: "cloud-run-ktor-hello-repo"
steps:
  - name: 'gradle:9.0.0-jdk21'
    id: 'build-image'
    dir: '.'
    entrypoint: bash
    args:
      - -c
      - |
        IMAGE="europe-west1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/cloud-run-ktor-hello"
        ./gradlew jib --no-daemon \
          -Djib.to.image="${IMAGE}" \
          -Djib.to.tags="latest,${COMMIT_SHA}"
